version: '3.8'

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: www-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    command: >
      sh -c "pnpm run dev"
    networks:
      - ui-network

  v4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storybook-agniflow
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:6006"
    command: >
      sh -c "pnpm storybook"
    networks:
      - ui-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - ui-network

networks:
  ui-network:
    driver: bridge
